name: primary
description: >-
  Allow you to gate your merge requests based on the status of jobs in your workflow.

on:
  workflow_dispatch:

jobs:
  all-check:
    name: Wait for all jobs to complete
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Build tests script
        run: make build-tests-ci
      - name: Run tests
        working-directory: Scripts/bin
        run: ./test-script
