name: primary
description: >-
  Allow you to gate your merge requests based on the status of jobs in your workflow.

jobs:
  all-check:
    name: Wait for all jobs to complete
    runs-on: default
    defaults:
      run:
        working-directory: Scripts/bin
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run tests
        run: ./test-script
